name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = "5750eb30-b806-4de5-ac91-77864727e992"

[[d1_databases]]
binding = "cloud_mail_db"
database_name = "cloud-mail-db"
database_id = "5750eb30-b806-4de5-ac91-77864727e992"

[[kv_namespaces]]
binding = "kv"
id = "5e854aef7c004278a7475577c3dfcca1"

[[kv_namespaces]]
binding = "KV"
id = "5e854aef7c004278a7475577c3dfcca1"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]

[vars]
domain = ["mailcat.co.za"]
admin = "admin@mailcat.co.za"

[[routes]]
pattern = "mail.mailcat.co.za"
custom_domain = true

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"